export const ASYNCSTORAGE_SESSION_KEY = "session_atma";
export const ASYNCSTORAGE_INTRO_PASS_KEY = "intro_pass_atma";

export const DEFAULT_BOX_PADDING_HORIZONTAL = 25;
export const DEFAULT_BOX_PADDING_VERTICAL = 25;

export default {
  ASYNCSTORAGE_INTRO_PASS_KEY,
  ASYNCSTORAGE_SESSION_KEY,
  DEFAULT_BOX_PADDING_HORIZONTAL,
  DEFAULT_BOX_PADDING_VERTICAL,
};
